sebamarynissen/simtropolis-channel

.github/workflows/test.yaml
actions/fetch/action.yaml
actions/fetch/api-to-metadata.js
actions/fetch/fetch.js
actions/fetch/scrape.js
actions/fetch/test/faker.js
actions/fetch/test/integration-test.js
actions/fetch/util.js
package-lock.json
package.json

This PR adds support for fetching all uploads since the last run. This will allow setting up a cron job for periodically checking the STEX, instead of only running for specific files. The date of the last run is stored in the root of the repo under the `LAST_RUN` file.

feat: fetch all uploads since last run

---

.github/workflows/deploy.yaml

This PR ensures that the deployment to GitHub pages uses the root path instead of `/channel`. This means that the channel becomes available on https://sebamarynissen.github.io/simtropolis-channel instead of https://sebamarynissen.github.io/simtropolis-channel/channel. This will be especially better when running under a simtropolis domain name. Users then simply would have to add https://sc4pac.simtropolis.com to their channels in the gui.
Related: #29.

build: deploy to root instead of `/channel`

---

actions/fetch/downloader.js
actions/fetch/fetch.js
actions/fetch/test/integration-test.js
package-lock.json
package.json

This PR removes the resilience of the downloads, meaning that we only try to unzip stuff that actually has `Content-Type: application/zip` set as its header. Also, should an error occur during unzipping, it will fail gracefully instead of crashing the workflow - and potentially blocking the processing of other valid uploads.
On top of that, we've also added the possibility that an upload contains a `metadata.yaml` file as a separate upload, instead of being in the .zip. When this happens, the metadata.yaml does not get registered as an asset though.
@memo33: I'm not really sure whether this is a good idea though. At first I was convinced that it was, but on second thought it will probably confuse users if they want to download something manually and they have to choose between a zip and a …

feat: improve resilience of downloads

---

actions/fetch/api-to-metadata.js
actions/fetch/categories.js
actions/fetch/fetch.js
actions/fetch/scrape.js
actions/fetch/test/api-to-metadata-test.js
actions/fetch/test/descriptor-to-subfolder-test.js
actions/fetch/test/integration-test.js

This PR determines the [subfolder](https://memo33.github.io/sc4pac/#/metadata?id=subfolder) for the generated metadata based on the "file descriptor" from the STEX upload. Currently this is not yet included in the STEX api response, so we rely on the web scraping. This means that currently we rely on the scraping for 3 properties:
- description
- images
- file descriptor
Determining the subfolder happens based on the following map:
```yaml
dependency: 100-props-textures
residential: 200-residential
commercial: 300-commercial
industrial: 400-industrial
agricultural: 410-agriculture
utilities-water: 500-utilities
utilities-power: 500-utilities
utilities-garbage: 500-utilities
services-police: 610-safety
services-fire: 610-safety
services-education: 620-education
services-medical: 630-health …
```

feat: determine subfolder based on descriptor

---

README.md
actions/fetch/action.js
actions/fetch/downloader.js
actions/fetch/errors.js
actions/fetch/fetch.js
actions/fetch/permissions.js
actions/fetch/scrape.js
actions/fetch/test/faker.js
actions/fetch/test/integration-test.js
permissions.yaml

This PR improves the error handling for when Simtropolis returns an HTTP 400 or higher (like `429 Too many requests`, `403 Forbidding`, `503 Service Unavailable`).
Currently the action will simply throw an error. However, there's a case where we might actually *partially* succeed. Imagine for example the case where the STEX api returns 3 new uploads. The first one is handled without problems, the second one bumps into a 520, but the third one is again processed correctly. In this case, we could continue and create a PR for upload 1, and then advance the last run date to the update date of file 1, instead of the current time. We can't do this for upload 3, because this would advance the last run date too much, and hence upload 2 won't be processed again the next run.
What's your opinion on …

feat: improve Simtropolis error handling

---

actions/fetch/fetch.js
actions/fetch/test/integration-test.js

Apparently the STEX api returns 404 if it couldn't find any files that match the criteria, meaning that if we call it with a parameter `days=2`, but no files were updated during that period, then it won't return an empty array, but 404 and an error message. This is not actually an error for the action, so this PR makes sure this is gracefully handled.

fix: handle 404 for no new files

---

actions/fetch/fetch.js

Apparently we have to manually set `mode=updated`, even though the docs say this is the default. Looks like the default is actually `mode=submitted`, so we only received newly submitted files from the last x days, instead of both updated and submitted files.

fix: explicitly set fetch mode to updated

---

actions/create-prs/create-prs.js
actions/fetch/attempt.js
actions/fetch/check-previous-version.js
actions/fetch/downloader.js
actions/fetch/handle-upload.js
actions/fetch/patch-metadata.js
actions/fetch/test/integration-test.js
actions/fetch/test/patch-metadata-test.js

This PR implements the new naming convention as discussed in #42. This means that files now always get prefixed with the stex file id to ensure uniqueness. When a package changes names, the original stex title is kept, unless explicitly overridden.

feat: implement new naming convention

---

actions/fetch/handle-upload.js
actions/fetch/permissions.js
actions/fetch/test/integration-test.js
permissions.yaml

This PR adds the functionality to automatically strip prefixes from STEX titles. This is needed because certain creators prefix the title of their content, such as `SM2 Concrete Sound Barriers`. It doesn't make sense to transform this into the name `simmer2:sm2-concrete-sound-barriers`, so we strip this from the title automatically.

feat: automatically strip prefixes

---

actions/fetch/parse-description.js
actions/fetch/test/integration-test.js

This PR transforms `<iframe>`'s in the description to links. This is useful when dependencies are included as an embedded iframe.

feat: transform `<iframe>` to links

---

src/yaml/aldara6166/17557-modular-amusement-park-pack-essentials.yaml
src/yaml/aldara6166/17558-modular-amusement-park-pack-classic-rides.yaml
src/yaml/aldara6166/17559-modular-amusement-park-pack-modern-rides.yaml
src/yaml/aldara6166/17560-modular-amusement-park-pack-roller-coasters.yaml

This PR adds [aldera6166](https://community.simtropolis.com/profile/53084-aldara6166/content/?type=downloads_file)'s modular amusement park pack.

metadata: add modular amusement park pack

---

actions/create-prs/create-prs.js
actions/fetch/handle-upload.js
actions/fetch/permissions.js
actions/fetch/test/integration-test.js
permissions.yaml

Following #67, the bot should now automatically tag GitHub users if the linting fails. This is also relevant for #37, as tying a ST user to a GitHub user will be needed.

feat: tag known GitHub users if linting fails

---

actions/fetch/permissions.js
actions/fetch/test/integration-test.js

Due to a bug, the Github usernames are not mentioned in the failing PRs (see #68).

fix: Github usernames are not logged in PRs

---

actions/create-prs/create-prs.js
actions/fetch/api-to-metadata.js
actions/fetch/handle-upload.js
actions/fetch/permissions.js
actions/fetch/test/api-to-metadata-test.js
actions/fetch/test/integration-test.js

This PR adds a few improvements to how the bot generates PRs, as obvserved in #67:
- If there's a permissions error - e.g. a user uploads under a group name they're not allowed to - the PR will still be created, but it won't get merged because and the error will be commented by the bot.
- When new metadata is uploaded for an open PR, the bot no longer reposts the updated metadata as a comment, but rather updates the body of the PR - i.e. the first comment in the PR.
- Titles that would compile to `vol-01` are getting the hyphen removed to pass the linter.

feat: improve PR generation

---

actions/fetch/handle-upload.js
actions/fetch/test/integration-test.js

Apparently the last fetch actions failed because https://community.simtropolis.com/files/file/15582-cogeo-logistics-centre-dependency-pack-v2/ has been made obsolete. This caused the STEX API to return
```json
[
{
"id": 15583,
"cid": 118,
"uid": 45188,
"author": "cogeo",
"category": "Dependencies",
"title": "Warehouses BATProps Part B",
"release": "OBSOLETE",
"submitted": "2006-04-08 16:26:21",
"updated": "2025-01-10 00:36:20",
"views": 63147,
"downloads": 27433,
"reputation": 10,
"sizeTotal": "0 bytes",
"files": [
{
"id": 205213,
"name": null,
"link": "https:\/\/community.simtropolis.com\/files\/file\/15582-cogeo-logistics-centre-dependency-pack-v2\/",
"size": "0 bytes"
}
],
"imageURL": "https:\/\/www.simtropolis.com\/objects\/screens\/0019\/acf131803459f15db092134547827637-WBLeft.jpg", …
```

fix: handle uploads without files

---

README.md
actions/create-prs/create-prs.js
actions/fetch/downloader.js
actions/fetch/handle-upload.js
actions/fetch/test/integration-test.js

In the wake of #67, this PR adds support for `metadata.yaml` files that are not located in the root of the upload. In order to make this possible, an error will now be logged if multiple `metadata.yaml` files are found in the assets.
TL;DR: From now on, only 1 `metadata.yaml` file can exist, but you can place it anywhere you like.
cc @noah-severyn

feat: support `metadata.yaml` in nested folders

---

package.json
scripts/list-dependencies.js

This PR adds a new script `npm run list`. It can be used to generate a list of dependencies in [standardized format](https://github.com/sebamarynissen/simtropolis-channel/issues/2). It will generate an `.html` file in `dist/copy.html`, which shows the dependency list as an html `<ul>` list. Click "Copy" to copy it to the clipboard.
When pasting it inside a wysiwyg editor - such as the description edit box on the STEX, or in an e-mail client - it will paste it as an actual html list. If pasting inside something that only supports text - such as text editors - it will paste the list in sc4pac format.
Example usage:
```
npm run list mattb325:ikea-superstore
```
Which results in the generated html:
- [bsc:mega-props-cp-vol02](https://www.sc4evermore.com/index.php/downloads/download/3-sc4d-lex- …

feat: add `npm run list` script

---

scripts/list-dependencies.js

This fixes a bug in #93 where a link was shown, even if the package has no website set. While it is preferrable that every package on sc4pac has a website attached to it, not all package do this (some for historical reasons). Hence, if a package has no website, we should render a link so that it's clear incentive to add a website.

fix: don't generate links without websites

---

src/yaml/peg/11129-refuse-relocation-kit.yaml
src/yaml/peg/11210-alley-kit.yaml

When installing `peg:refuse-relocation-kit` you have to choose a color of the Garbage trucks. The metadata did not include this, but does so now.

fix: add variants to `peg:refuse-relocation-kit`

---

scripts/list-dependencies.js

This PR improves the `npm run list` script so that it can now list dependencies for multiple packages in the same `.html` document. You can now specify multiple packages, as well as use glob patterns:
```
npm run list mattb325:ikea-superstore parisian:*
```
On top of that, we've also added a `--default-only` flag. If this flag is used, only packages that are present on the default channel will get their dependency link rendered as `group:name`. If the package is *not* in the default channel, then the link is still rendered, but the visible text is just the author and summary of the package.
Example usage with `--default-only` (note: the `--` is needed to pass the `--default-only` option down to the script, otherwise Node interprets it as an npm option).
```
npm run list -- simmer2:5g-* …
```

feat: list dependencies for multiple packages

---

actions/fetch/test/api-to-metadata-test.js
actions/fetch/test/integration-test.js
actions/fetch/util.js

This PR changes the way apostrophes in the package title are handled when transforming it to the name. Instead of replacing them with a hyphen, they are now simply omitted, so that "Andrew's Fashion Centre" becomes `andrews-fashion-centre` instead of `andrew-s-fashion-centre`.
Related: #103.

feat: don't replace apostrophes with hyphens

---

scripts/sc4pac.js
scripts/standard-deps.js
scripts/standard-variants.js

Following a discussion in #104, this PR adds `peg:oops-mod` to the standard dependencies, and also allows you to specify additional ones as a comma-separated list in a variable `STANDARD_DEPENDENCIES` in your `.env` file.
On top of that, it also allows you to specify the default variants with `STANDARD_VARIANTS`. That way you don't always have to specify the different variants manually when running `npm run sc4pac`.
Example `.env` file:
```.env
STANDARD_DEPENDENCIES=memo:submenus-dll,lowkee33:appalachian-terrain-mod-complete
STANDARD_VARIANTS=nightmode=dark,driveside=right,sfbt:essentials:tree-family=Maxis-deciduous-trees
```
cc @noah-severyn

feat: allow additional standard dependencies in `.env`

---

extensions/build/build.js
extensions/src/manifest.json

Now that the "Install with sc4pac" button is live on Simtropolis, we no longer need it as part of the extensions. The only thing the extension still needs to do is copying the credentials to the clipboard. The script that is added on Simtropolis is now built separately as part of `npm run build:extensions`.

build: remove install button from extensions

---

scripts/standard-deps.js

fix: don't introduce empty dependencies when no `STANDARD_DEPENDENCIES` env variable is found

---

actions/fetch/api-to-metadata.js
actions/fetch/fetch-all.js
scripts/manual-add.js

See #121. This PR adds a `--darknite-only` flag to the `npm run add` script so that every asset is forcibly tagged as darknite, so that the correct variants get generated. This is useful in case an author uploaded a plugin as darknite-only, but did not label the asset as such.
cc @noah-severyn

feat: support `--darknite-only` flag

---

src/yaml/aldara6166/17557-modular-amusement-park-pack-essentials.yaml

This PR updates the Modular Amusement Park Pack Essentials so that it no longer includes the MML, but provides it as a separate package.

fix: remove MML from MAPP

---

actions/fetch/stylize-doc.js
actions/fetch/test/integration-test.js

This PR fixes an issue where the linter reports an error if a boolean-like value such as "off" or "yes" is unquoted. The linter treats this as a boolean, whereas the yaml module apparently does not. We will now force quote anything like that.
Related: #144.

fix: properly quote boolean-like values

---

actions/fetch/stylize-doc.js
actions/fetch/test/integration-test.js

This PR fixes a bug introduced in #146 where keys like `description` would also get quoted because of an incorrect regex.

fix: fix accidental double quoting

---

actions/fetch/handle-upload.js
scripts/standard-deps.js
src/yaml/peg/10897-rtk3-recreational-style.yaml
src/yaml/peg/10934-rtk3-rec-addon1.yaml
src/yaml/peg/11054-seasonal-trail-parks.yaml
src/yaml/peg/11334-observation-tower.yaml
src/yaml/peg/11775-cdk-rec-prop-pack-1.yaml
src/yaml/peg/12007-cdk-oww-development-pack-vol1.yaml
src/yaml/peg/13059-trail-park-fountain-plaza.yaml
src/yaml/peg/14026-mtp-random-pine-forest.yaml
src/yaml/peg/14055-mtp-mountain-trail-rail-crossing.yaml
src/yaml/peg/14058-mtp-mountain-trail-fire-circle.yaml
src/yaml/peg/14097-mtp-forest-pack-1.yaml
src/yaml/peg/14107-mtp-low-wealth-growable-res-cabins.yaml
src/yaml/peg/14158-mtp-high-wealth-growable-res-lodges.yaml
src/yaml/peg/14241-mtp-urgent-care-clinic.yaml
src/yaml/peg/14250-mtp-old-school-house.yaml
src/yaml/peg/14379-mtp-santas-village-alternate-audio.yaml
src/yaml/peg/14586-mtp-no-roadway-junk-mod.yaml
src/yaml/peg/14620-mtp-rural-roadways-mod.yaml
src/yaml/peg/14809-mtp-scenic-views.yaml
src/yaml/peg/14810-mtp-sway-bridge.yaml
src/yaml/peg/15794-mtp-res-replacement-mod.yaml
src/yaml/peg/30651-santas-village.yaml
src/yaml/peg/4515-mtp-seasonal-woods.yaml
src/yaml/peg/4523-pine-forest.yaml
src/yaml/peg/4526-mtp-random-woods.yaml
src/yaml/peg/4530-rtk3-watertreatment-plant.yaml

This PR adds bunch of Peg's content, most notably from the Mountain Theme Pack.
Note: we had to exclude the https://community.simtropolis.com/files/file/15794-peg-mtp-res-replacement-mod/ because apparently it is broken. The R$ lots seem to reference the wrong building exemplars.

metadata: add more of Peg's content

---

actions/fetch/handle-upload.js

Apparently the recent publishing of the [NAM](https://community.simtropolis.com/files/file/35417-network-addon-mod-lite-nam-lite-cross-platform/) broke the channel because the upload doesn't contain a file name. We already properly handled `file.name === null`, but in this case it's simply not present.

fix: handle uploads without names

---

actions/fetch/stylize-doc.js

Apparently the channel crashes on the `metadata.yaml` file from [this upload](https://community.simtropolis.com/files/file/36757-dsc-elrail-glasgow-subway-tram-version/). It should be noted that the metadata.yaml is horribly, horribly wrong, but still, the channel should not crash on it and create the PR.

fix: crash on empty dependencies

---

actions/fetch/downloader.js

Apparently we have to set the `User-Agent` to sc4pac, otherwise the authentication token isn't properly recognized and we risk running into `429 Too Many Requests` errors.
@noah-severyn Related to #192

fix: use sc4pac user agent

---

src/yaml/sg/14522-public-pools-pack.yaml

This adds one SimGoober package: https://community.simtropolis.com/files/file/14522-public-pools-pack/
In general, how much should the descriptions be cleaned up? I've taken the output of `npm run add` directly, for now.
Also, an observation: The STEX entry contains a link to https://community.simtropolis.com/sc4-maxis-files/ for the nightlight patch (…the SG files are that old), which the `parse-dependencies.js` script turns into a `maxis:buildings-as-props` dependency. I understand why though – it doesn't really require fixing.

metadata: add `sg:public-pools-pack`

---

src/yaml/tiepinl/37015-block-maxis-rci-lots.yaml

This PR adds metadata for TiepiNL's Block Maxis RCI Lots mod to sc4pac.
- **tiepinl:block-maxis-i-d** - Block Maxis Industrial Dirty lots
- **tiepinl:block-maxis-i-m** - Block Maxis Industrial Manufacturing lots  
- **tiepinl:block-maxis-i-ht** - Block Maxis Industrial High-Tech lots
- **tiepinl:block-maxis-i-r** - Block Maxis Industrial Resource lots
- **tiepinl:block-maxis-residential** - Block Maxis Residential lots
- **tiepinl:block-maxis-commercial** - Block Maxis Commercial lots
- **tiepinl:block-maxis-CAM** - Block CAM commercial lots based on Maxis Landmarks
- **STEX URL:** https://community.simtropolis.com/files/file/37015-block-maxis-rci-lots/
- **Version:** 1.1
- **Modern exemplar patching approach** - no loading order dependencies
- **CAM variant support** - can be …

metadata: add TiepiNL's content
