- actions/fetch/downloader.js
- actions/fetch/test/integration-test.js
Apparently the ST authentication cookies were not properly sent when downloading. This PR fixes that.
> fix: properly include cookie when downloading

- actions/fetch/complete-metadata.js
- actions/fetch/fetch-all.js
- actions/fetch/handle-upload.js
- package-lock.json
- package.json
This PR exposes a `fetchAll` function that can be used to re-use the same logic as the channel to generate automatic metadata.
> feat: expose `fetch-all.js`

- actions/fetch/api-to-metadata.js
- actions/fetch/complete-metadata.js
- actions/fetch/downloader.js
- actions/fetch/fetch-all.js
- actions/fetch/polyfill.js
- actions/fetch/symbols.js
- actions/fetch/test/api-to-metadata-test.js
- actions/fetch/test/expand-variants-test.js
This PR improves the automatic detection & generation of variant metadata. It now handles HD/SD and CAM as well, as long as it follows a certain convention - still to be document in the readme though once we've finalized this. The convention is based on what [Jasoncw](https://community.simtropolis.com/profile/85340-jasoncw/content/?type=downloads_file&sortby=file_submitted&sortdirection=desc) is using in his uploads, most notably the [Guardian Building](https://community.simtropolis.com/files/file/32737-guardian-building/).
> feat: improve automatic variant detection

- actions/fetch/complete-metadata.js
- actions/fetch/test/integration-test.js
This PR adds support for specifying Maxisnite and Darknite variants *in the same asset*. This is a convention used for example by mattb325 in his [earlier](https://community.simtropolis.com/files/file/28644-harbor-clinic/) [uploads](https://community.simtropolis.com/files/file/30865-car-yard-by-mattb325/).
Still needs to be document in the readme, however, this approach should be discouraged. The preferred way of specifying MN/DN variants is by having two separate assets.
> feat: add support for MN/DN in same asset

- src/yaml/fribe/27014-nighthawks-stadium.yaml
- src/yaml/fribe/27255-bighorn-bowl.yaml
- src/yaml/fribe/27371-elmer-s-nursery.yaml
- src/yaml/fribe/27389-bowman-gray-stadium.yaml
- src/yaml/fribe/27586-arctic-circle-ice-cream.yaml
- src/yaml/fribe/27657-talbot-speedway.yaml
- src/yaml/fribe/27853-creek-park-stadium.yaml
- src/yaml/fribe/27899-43-brothers-pizza.yaml
- src/yaml/fribe/28019-hemphill-place.yaml
- src/yaml/fribe/28138-royal-farms.yaml
- src/yaml/fribe/28499-back-river-wastewater-treatment-plant.yaml
- src/yaml/fribe/28529-telegraph-inn.yaml
- src/yaml/fribe/28601-brewer-stadium.yaml
- src/yaml/fribe/28602-brewer-stadium-canada-edition.yaml
- src/yaml/fribe/28664-mallow-park.yaml
- src/yaml/fribe/28736-beachcomber-tower.yaml
This PR adds all of [fribe](https://community.simtropolis.com/profile/373522-fribe/content/?type=downloads_file)'s content.
> Add fribe's content

- permissions.yaml
- src/yaml/deadwoods/16556-highway-walls.yaml
Adds https://community.simtropolis.com/files/file/16556-dedwd-highway-walls/
> Add `deadwoods:highway-walls`

- actions/create-prs/create-prs.js
See #67. @noah-severyn looks like you did indeed find a nice edge case. Apparently the action failed when a filename changed *within* the same PR. This should fix that.
> fix: handle removed files within a PR

- src/yaml/yticmic/10935-western-duplex.yaml
- src/yaml/yticmic/10946-aluminium-rowhomes.yaml
- src/yaml/yticmic/10947-titanium-rowhomes.yaml
- src/yaml/yticmic/11278-western-duplex-version-2.yaml
- src/yaml/yticmic/11279-small-wooden-house.yaml
- src/yaml/yticmic/11311-small-lofts.yaml
- src/yaml/yticmic/11312-small-lofts-sandstone.yaml
- src/yaml/yticmic/11319-mcorp-offices.yaml
- src/yaml/yticmic/11332-minicorp-industrials.yaml
- src/yaml/yticmic/12504-stone-terraces-mixed-use.yaml
- src/yaml/yticmic/12513-the-saint-louis.yaml
- src/yaml/yticmic/12516-pizza-hut-express.yaml
- src/yaml/yticmic/12518-mellon-apartments.yaml
- src/yaml/yticmic/12549-the-carbon-building.yaml
- src/yaml/yticmic/12577-deco-incorporated.yaml
- src/yaml/yticmic/12590-mcorp-offices-update.yaml
- src/yaml/yticmic/12591-modern-rowhomes-updated.yaml
- src/yaml/yticmic/12603-small-lofts-updated.yaml
- src/yaml/yticmic/14405-small-theater-pack.yaml
- src/yaml/yticmic/16264-christophers-bar.yaml
- src/yaml/yticmic/16265-corner-shops.yaml
- src/yaml/yticmic/16266-woodstock-candies.yaml
This PR adds all of [yticmic's](https://community.simtropolis.com/profile/7895-yticmic/content/?type=downloads_file) content.
> Add yticmic's content

- actions/fetch/generate-variants.js
- actions/fetch/scrape.js
- actions/fetch/test/integration-test.js
- permissions.yaml
- src/yaml/jawood/3595-aspen-village-condominiums-multi-color-version.yaml
- src/yaml/jawood/4117-splash-point-water-park-water-slide-tower.yaml
- src/yaml/jawood/4144-splash-point-water-park-wave-pool.yaml
- src/yaml/jawood/4229-splash-point-water-park-front-entrance.yaml
- src/yaml/seraf/23070-new-york-county-supreme-court.yaml
- src/yaml/seraf/23408-michigan-central-station.yaml
- src/yaml/seraf/24300-central-park-cherry-hill-fountain.yaml
- src/yaml/seraf/24323-joseph-pulitzer-fountain.yaml
- src/yaml/seraf/24989-metropolitan-club.yaml
- src/yaml/seraf/25829-alexander-hamilton-u-s-custom-house.yaml
- src/yaml/seraf/26686-elder-park-rotunda.yaml
- src/yaml/seraf/27128-kaiser-wilhelm-nationaldenkmal.yaml
- src/yaml/seraf/28501-jamesfarley-post-office.yaml
- src/yaml/seraf/29856-university-club-of-new-york.yaml
- src/yaml/seraf/29887-city-hall-park-fountain.yaml
- src/yaml/seraf/30206-leaning-tower-of-pisa.yaml
- src/yaml/seraf/30705-new-york-life-insurance-company-annex.yaml
- src/yaml/seraf/30849-hotel-pennsylvania.yaml
- src/yaml/seraf/31865-courthouse-of-the-appellate-division.yaml
- src/yaml/seraf/31866-nos-31-33-madison-avenue.yaml
- src/yaml/seraf/33115-battle-monument-west-point.yaml
- src/yaml/swordmaster/28243-minimize-button-remover.yaml
This PR adds most of [Seraf's content](https://community.simtropolis.com/profile/157985-seraf/content/?type=downloads_file&sortby=file_submitted&sortdirection=desc).
> metadata: add Seraf's content

- actions/fetch/test/api-to-metadata-test.js
- actions/fetch/util.js
Fixes https://github.com/sebamarynissen/simtropolis-channel/pull/78#issuecomment-2599792563.
> fix: normalize diacrtics in summary

- scripts/prune.js
This PR allows you to specify what packages need to be pruned by using glob patterns.
Example usage:
```
npm run prune -- mattb325:* diego-del-lano:432-park-avenue --force
```
cc @noah-severyn
> feat: allow specifying packages to be pruned

- permissions.yaml
- src/yaml/parisian/24915-morgan-court-sliver-building-v1.yaml
- src/yaml/parisian/24924-the-w-times-square.yaml
- src/yaml/parisian/27264-paramount-appartments-tower.yaml
- src/yaml/parisian/27654-cartier-versace-stores-fifth-ave.yaml
- src/yaml/parisian/27689-louis-vuitton-fifth-ave.yaml
- src/yaml/parisian/28496-gotham-style-monumental-lights.yaml
- src/yaml/parisian/28497-ed-koch-queensboro-bridge-1909-lamppost.yaml
- src/yaml/parisian/28616-712-fifth-avenue.yaml
- src/yaml/parisian/28661-the-four-seasons-hotel-tower.yaml
- src/yaml/parisian/30022-tudor-city-tudor-tower.yaml
- src/yaml/parisian/30023-tudor-city-prospect-tower.yaml
- src/yaml/parisian/30025-tudor-city-windsor-tower.yaml
- src/yaml/parisian/31429-the-crown-building-new-york.yaml
- src/yaml/parisian/32012-the-tudor-city-new-york.yaml
- src/yaml/parisian/35233-morgan-court-sliver-building.yaml
This PR adds all of [Parisian's content](https://community.simtropolis.com/profile/217422-parisian/content/?type=downloads_file&sortby=file_submitted&sortdirection=desc)
> metadata: add Parisian's content

- src/yaml/odainsaker/16648-tower-life-building.yaml
- src/yaml/odainsaker/18706-casino-club.yaml
- src/yaml/odainsaker/19227-tower-of-the-americas.yaml
- src/yaml/odainsaker/20076-alexander-column.yaml
- src/yaml/odainsaker/20103-alexander-column-roundabouts.yaml
- src/yaml/odainsaker/20775-broadway-mansions.yaml
- src/yaml/odainsaker/24036-vogue-department-store.yaml
Inspired by https://community.simtropolis.com/forums/topic/763573-rest-in-peace-odainsaker/
> Add odainsaker's content

- README.md
@memo33 Can you give this a proof-read? I'm not sure how clear it's going to be for new users that have very little experience with sc4pac or yaml.
Note: I've written the section about HD/SD to use a non-global variant, but I still have to implement it like this.
> docs: improve documentation for launch

- src/yaml/coultharda/14159-5aside-football-centre.yaml
- src/yaml/coultharda/15023-dover-road-moneyfields-fc.yaml
- src/yaml/coultharda/15171-victory-stadium.yaml
- src/yaml/coultharda/15493-ill-tonkso-stadium.yaml
- src/yaml/coultharda/15538-nuffield-stadium.yaml
- src/yaml/coultharda/15909-all-weather-pitch.yaml
- src/yaml/coultharda/16551-ill-tonkso-park-v2.yaml
- src/yaml/coultharda/16738-dixon-kennedy-stadium.yaml
- src/yaml/coultharda/16868-sobcitski-stadium.yaml
- src/yaml/coultharda/17505-freya-park.yaml
- src/yaml/coultharda/17585-generic-modern-uk-stadium.yaml
- src/yaml/coultharda/17921-small-football-ground.yaml
- src/yaml/coultharda/18016-small-football-ground-2.yaml
- src/yaml/coultharda/18023-david-collett-stadium.yaml
- src/yaml/coultharda/18045-small-football-ground-3.yaml
- src/yaml/coultharda/18153-river-park-stadium.yaml
- src/yaml/coultharda/18641-small-football-ground-4.yaml
- src/yaml/coultharda/25507-all-weather-hockey-and-football-pitch.yaml
- src/yaml/coultharda/33690-small-football-ground-5.yaml
- src/yaml/coultharda/33692-small-rugby-stadium.yaml
- src/yaml/coultharda/33696-small-football-stadium.yaml
This PR adds all of [coultharda's content](https://community.simtropolis.com/profile/26154-coultharda/content/?type=downloads_file).
> metadata: add Coultharda's content

- src/yaml/hund88/20099-european-bus-stops.yaml
- src/yaml/hund88/20133-massive-storage-inc.yaml
- src/yaml/hund88/20140-open-air-swimming-pool.yaml
- src/yaml/hund88/20152-ohm-resistors.yaml
- src/yaml/hund88/20161-warehouse.yaml
- src/yaml/hund88/20173-nova-energetics.yaml
- src/yaml/hund88/20247-djami.yaml
- src/yaml/hund88/20277-bakery.yaml
- src/yaml/hund88/20480-effectimed.yaml
- src/yaml/hund88/20604-quetz-isoprenes-co.yaml
- src/yaml/hund88/21219-grain-field.yaml
- src/yaml/hund88/21381-apt-inc.yaml
- src/yaml/hund88/22686-bauxim-al-co.yaml
Add content by [Hund88](https://community.simtropolis.com/profile/183541-hund88/?do=content&type=downloads_file). Most items have been split out into model packages as they'll be used later, mainly for the IRM Expansion sets.
> Add Hund88's content

- src/yaml/nique/29875-modular-noise-barriers-brown.yaml
This PR adds https://community.simtropolis.com/files/file/29875-niques-modular-noise-barriers-brown/
> metadata: add `nique:modular-noise-barriers`

- src/yaml/simmer2/32701-center-pivot-irrigation-fields.yaml
This PR splits https://community.simtropolis.com/files/file/32701-sm2-center-pivot-irrigation-fields/ into resources and lots for relotting usage.
> metadata: split `simmer2:center-pivot-irrigation-fields`

- src/yaml/delecto/23092-delecto-pearl-sunshine.yaml
- src/yaml/delecto/29171-delecto-essentials-files.yaml
- src/yaml/delecto/29175-delecto-abelia-residence.yaml
- src/yaml/delecto/29178-delecto-costa-obzor.yaml
Add [Delecto's](https://community.simtropolis.com/profile/248178-delecto/content/?type=downloads_file) content.
> Add Delecto's content

- src/yaml/roe99/23111-grandiosedometower.yaml
- src/yaml/roe99/23112-grandiosedomeg7.yaml
- src/yaml/roe99/23300-state-fair-market.yaml
- src/yaml/roe99/23406-pasar-tanah-abang.yaml
- src/yaml/roe99/23432-elsha-condoz.yaml
- src/yaml/roe99/23478-menara-imperium.yaml
- src/yaml/roe99/23527-gkbi-tower.yaml
- src/yaml/roe99/23567-talavera-office-park.yaml
- src/yaml/roe99/23622-sentra-mulia-tower.yaml
- src/yaml/roe99/23667-menara-batavia-update.yaml
- src/yaml/roe99/23838-the-peak-part1.yaml
- src/yaml/roe99/23839-da-vinci-update.yaml
- src/yaml/roe99/23849-the-peak-final.yaml
- src/yaml/roe99/24213-transjakarta-busway.yaml
- src/yaml/roe99/24215-soeman-hs-riau-library.yaml
- src/yaml/roe99/24216-repaint-maxis-ferry.yaml
- src/yaml/roe99/24217-elsha-watermod.yaml
- src/yaml/roe99/24218-garuda-indonesia-airline.yaml
- src/yaml/roe99/24219-singapore-airlines-747-400.yaml
- src/yaml/roe99/24221-thai-airlines-a340-600-and-a330-200.yaml
- src/yaml/roe99/24222-malaysia-airlines-and-airasia-darkblue.yaml
- src/yaml/roe99/24412-regatta.yaml
- src/yaml/roe99/26196-bundaran-hi.yaml
- src/yaml/roe99/26200-wisma46-v2.yaml
- src/yaml/roe99/26364-area-24.yaml
- src/yaml/roe99/26406-equity-tower.yaml
- src/yaml/roe99/26505-mnc-tower.yaml
- src/yaml/roe99/32448-monas-monument.yaml
Add [Roe99's](https://community.simtropolis.com/profile/279773-roe99/content/?type=downloads_file) content.
> Add Roe99's Content

- permissions.yaml
- src/yaml/pbgv103/22870-885-3rd-avenue.yaml
- src/yaml/pbgv103/22909-us-armed-forces-recruiting-station.yaml
- src/yaml/pbgv103/23307-570-560-lexington-v2.yaml
- src/yaml/pbgv103/24301-mutual-of-america-building.yaml
- src/yaml/pbgv103/26060-425-lexington-avenue.yaml
This PR adds all of [PBGV103's content](https://community.simtropolis.com/profile/286851-pbgv103/content/?type=downloads_file).
> metadata: add PBGV103's content

- src/yaml/doctorgonzo/2643-artgolf-golf-course.yaml
- src/yaml/peg/22701-ppond-terrain-props-pack-1.yaml
- src/yaml/sim-idiot/3228-sc-golf-pack.yaml
- src/yaml/skimbo/25700-sc4-golf-pack.yaml
This PR adds 3 golf courses:
- https://community.simtropolis.com/files/file/25700-skimbos-sc4-golf-pack/
- https://community.simtropolis.com/files/file/2643-artgolf-golf-course/
- https://community.simtropolis.com/files/file/3228-sc-golf-pack/
> metadata: add golf courses

- permissions.yaml
- src/yaml/joerg/1844-sim-high.yaml
- src/yaml/joerg/1976-golf-pack.yaml
- src/yaml/joerg/2431-sim-metro-life-arena.yaml
- src/yaml/joerg/811-the-rich-guys-place.yaml
- src/yaml/shadow-assassin/15363-cycleways-basic-pack.yaml
- src/yaml/shadow-assassin/15534-cycleways-expansion-pack-1.yaml
- src/yaml/timo/11426-stade-de-france-v1.yaml
- src/yaml/timo/11770-stade-de-france-v3-rugby-stadium.yaml
This PR adds some packages from my old personal plugins folder
> Add various packages

- permissions.yaml
- src/yaml/goldiva/13067-mayor-mode-tropical-tree-set.yaml
- src/yaml/goldiva/13068-mayor-mode-tropical-sea-set.yaml
- src/yaml/goldiva/3355-water-taxi-station-wbus-stop-new-water-taxi.yaml
- src/yaml/kergelen/27973-mmp-mediterranean-cp-trees-krg-selection.yaml
- src/yaml/peg/21661-ppond-kit.yaml
This PR adds various MMP packs:
- https://community.simtropolis.com/files/file/13067-gdv-mayor-mode-tropical-tree-set/
- https://community.simtropolis.com/files/file/13068-gdv-mayor-mode-tropical-sea-set/
- https://community.simtropolis.com/files/file/27973-mmp-mediterranean-cp-trees-krg-selection/
- https://community.simtropolis.com/files/file/21661-peg-ppond-kit/
> Add various mmp packs

- src/yaml/onlyplace4/17861-blam-signage-volume-1.yaml
- src/yaml/onlyplace4/17862-blam-signage-volume-2.yaml
- src/yaml/onlyplace4/17870-blam-signage-volume-3.yaml
> Add BLaM Signage props

- actions/fetch/fetch.js
- permissions.yaml
- scripts/manual-add.js
- scripts/sc4d.js
- src/yaml/anotn/26685-mott-haven-corner.yaml
- src/yaml/anotn/27039-the-aurora.yaml
- src/yaml/anotn/27274-augustenborg-houses.yaml
- src/yaml/anotn/28222-345-seventh-avenue.yaml
This PR adds [anotn's](https://community.simtropolis.com/profile/25774-anotn/content/?type=downloads_file) content.
> metadata: add anotn's content

- src/yaml/11241036/33702-vip-trees-as-props.yaml
This PR adds https://community.simtropolis.com/files/file/33702-vip-trees-as-props/
> metadata: add `11241036:vip-trees-as-props`

- src/yaml/kellydale2003/19735-atlantic-records-construction.yaml
- src/yaml/kellydale2003/26805-kingston-developments-ltd-under-construction.yaml
- src/yaml/kellydale2003/26817-james-richardson-and-sons-ltd-hq.yaml
- src/yaml/kellydale2003/27269-centre-place-bank-of-moscow.yaml
- src/yaml/kellydale2003/27565-linda-swampy-medical-centre.yaml
- src/yaml/kellydale2003/28333-absolute-city-centre-absolute-world-one.yaml
- src/yaml/kellydale2003/28347-1001-yonge-st-offices-and-library.yaml
- src/yaml/kellydale2003/28348-vohcem-condominiums.yaml
- src/yaml/kellydale2003/28361-eicosakis-biology-research-centre.yaml
- src/yaml/kellydale2003/29041-11-king-street-west.yaml
- src/yaml/kellydale2003/29054-u-of-w-science-complex.yaml
- src/yaml/kellydale2003/29061-paris-building.yaml
- src/yaml/kellydale2003/30475-bay-adelaide-centre-west.yaml
- src/yaml/kellydale2003/31862-ritz-carlton-toronto.yaml
- src/yaml/kellydale2003/31868-palais-garnier-remastered.yaml
- src/yaml/kellydale2003/31873-eighth-avenue-place-east-tower.yaml
- src/yaml/kellydale2003/32474-royal-bank-of-sims.yaml
- src/yaml/kellydale2003/32500-scotia-plaza-toronto.yaml
- src/yaml/kellydale2003/32614-the-bow-calgary-canada.yaml
- src/yaml/kellydale2003/32618-300-main-residences-winnipeg-canada.yaml
- src/yaml/kellydale2003/32691-cn-tower-new-years-day-version.yaml
- src/yaml/kellydale2003/32722-royal-bank-plaza-toronto.yaml
- src/yaml/kellydale2003/32725-four-seasons-hotel-and-residences-toronto.yaml
- src/yaml/kellydale2003/34097-apple-hq-beta-version.yaml
Add [Kellydale2003's](https://community.simtropolis.com/profile/147539-kellydale2003/?do=content&type=downloads_file) content. Pending their response for [one building](https://community.simtropolis.com/files/file/31873-eighth-avenue-place-east-tower) with immortal lot syndrome. If approved I'll update the file with a fix.
> Add Kellydale2003's content

- src/yaml/boon1234/19771-plopable-cows.yaml
- src/yaml/boon1234/23125-stop-maxis-mansions-from-growing.yaml
Add [boon1234](https://community.simtropolis.com/profile/86980-boon1234/content/?type=downloads_file)'c content. A nice small one. :)
The ploppable cows were added to the automata subfolder because they kind of roam around a bit (kinda similar to other automata generators), and that was the original STEX category.
> Add boon1234's content

- src/yaml/fluggi/23722-modern-bus-stops-update.yaml
- src/yaml/fluggi/24018-rhw4-toll-booth.yaml
- src/yaml/fluggi/24019-the-budchen.yaml
- src/yaml/khoianh94/23417-european-bus-and-tram-stops.yaml
- src/yaml/mrsnoopy/4003-toll-stations.yaml
Add [fluggi](https://community.simtropolis.com/profile/306846-fluggi/content/?type=downloads_file)'s content, plus related dependencies.
> Add fluggi's content

- src/yaml/victory/1001-academy-award-metro-station.yaml
- src/yaml/victory/1007-urban-public-school.yaml
- src/yaml/victory/1010-functioning-gateway-arch.yaml
- src/yaml/victory/1018-art-school-conversion.yaml
- src/yaml/victory/1032-public-housing-project.yaml
- src/yaml/victory/1099-downtown-athletic-club.yaml
- src/yaml/victory/1170-billy-bobs-food-emporium.yaml
- src/yaml/victory/600-majestic-drivein-theatre.yaml
- src/yaml/victory/619-amackassin-club-1888.yaml
- src/yaml/victory/626-farm-labor-camp.yaml
- src/yaml/victory/629-construction-equipment-yard.yaml
- src/yaml/victory/634-crop-duster-and-farm.yaml
- src/yaml/victory/639-acropolis-diner.yaml
- src/yaml/victory/646-hobo-jungle.yaml
- src/yaml/victory/659-grand-tunis-landmark-hotel.yaml
- src/yaml/victory/678-planetarium-and-seti-center.yaml
- src/yaml/victory/682-landmark-helicopter-tours.yaml
- src/yaml/victory/697-the-bates-motel.yaml
- src/yaml/victory/737-new-york-street-festival.yaml
- src/yaml/victory/752-suburban-back-alleys.yaml
- src/yaml/victory/772-country-roads-set.yaml
- src/yaml/victory/849-downtown-roller-rink.yaml
- src/yaml/victory/892-urban-firehouse.yaml
- src/yaml/victory/896-downtown-high-school.yaml
- src/yaml/victory/923-academy-awards-theatre.yaml
- src/yaml/victory/954-hockey-venue.yaml
- src/yaml/victory/980-city-jail.yaml
Add [Victory](https://community.simtropolis.com/profile/6984-victory/content/?type=downloads_file)'s content. Some of the earlier uploads to the STEX which is neat.
> Add Victory's Content

- src/yaml/wannglondon/36213-medit-bldg-59.yaml
- src/yaml/wannglondon/36671-los-angeles-home-5.yaml
- src/yaml/wannglondon/36762-american-shops-pack-1.yaml
- src/yaml/wannglondon/36768-california-bungalow-pack.yaml
- src/yaml/wannglondon/36814-los-angeles-home-7.yaml
This PR adds a bunch of content from [WannGLondon](https://community.simtropolis.com/profile/197802-wannglondon/content/?type=downloads_file) that came out or got updated after #58.
> metadata: add missing wannglondon content

- src/yaml/meinhosen/17000-american-traffic-generating-lots.yaml
- src/yaml/mikeseith/14400-european-cars-automata-and-family-props-new-instances.yaml
- src/yaml/mikeseith/16257-euro-traffic-generator.yaml
This PR adds two traffic generators and their dependencies:
- https://community.simtropolis.com/files/file/16257-euro-traffic-generator/
- https://community.simtropolis.com/files/file/17000-american-traffic-generating-lots/
> metadata: add traffic generating lots

- src/yaml/ids2/36778-tj-maxx-and-homegoods.yaml
- src/yaml/ids2/36780-lalumiere-hall.yaml
- src/yaml/ids2/36800-equitable-building.yaml
This PR adds a few of ids2's [recent packages](https://community.simtropolis.com/profile/70889-ids2/content/?type=downloads_file):
- https://community.simtropolis.com/files/file/36780-lalumiere-hall/
- https://community.simtropolis.com/files/file/36778-tj-maxx-and-homegoods/
- https://community.simtropolis.com/files/file/36800-equitable-building/
> metadata: add recent ids2 packages

- permissions.yaml
- scripts/sc4d.js
- src/yaml/delija21/21560-ruins.yaml
- src/yaml/evilcoolkid/20065-ww2-destroyed-buildings-v1.yaml
- src/yaml/evilcoolkid/20073-ww2-destroyed-buildings-v2.yaml
- src/yaml/johnb/3345-totem-pole.yaml
- src/yaml/peg/19362-cdk3-coast-guard-station.yaml
- src/yaml/simcoug/28307-maxis-rss-homes.yaml
- src/yaml/simcoug/28426-old-rs-neighborhoods.yaml
- src/yaml/simcoug/28630-rss-diagonal-homes.yaml
- src/yaml/simcoug/28957-peg-coast-guard-boats.yaml
- src/yaml/simcoug/29000-diagonal-w2w-tenements.yaml
- src/yaml/simcoug/30425-stairways.yaml
- src/yaml/simcoug/30688-cp-lodgepole-fence-mmp.yaml
- src/yaml/simcoug/30690-ruins-mmp.yaml
- src/yaml/simcoug/30807-semi-truck-cabs-vol1-mmp.yaml
- src/yaml/simcoug/30869-american-indian-prop-mmp.yaml
- src/yaml/simcoug/31753-little-well.yaml
- src/yaml/simcoug/31771-mattb325s-historic-shops.yaml
Adds all (well, most) of [Simcoug's content](https://community.simtropolis.com/profile/193070-simcoug/content/?type=downloads_file).
> metadata: add Simcoug's content

- src/yaml/leshan/29168-wind-power-plant-no-grass.yaml
- src/yaml/leshan/29173-1x1-slope-conforming-wind-power-plant.yaml
Add [Leshan's](https://community.simtropolis.com/profile/655168-leshan) content.
> metadata: add Leshan's content

- src/yaml/ulisse-wolf/35036-hybrid-railway-subway-converter.yaml
- src/yaml/ulisse-wolf/35234-mediterranean-transport-set-vol1.yaml
- src/yaml/ulisse-wolf/35635-five-nights-at-freddys.yaml
- src/yaml/ulisse-wolf/36616-fallout-common-dependencies-pack.yaml
- src/yaml/ulisse-wolf/36872-anno-2070-common-dependencies-pack.yaml
Although SC4Pac authorizes downloading from only one exchnage you can have a kind of cross exchange of the downlaod by putting in the metadata the website URL of Simtropolis and URL of another Exchange (TSC, SC4Evermore etc..)
This PR is to check if the simtropolis channel supports cross exchange and possibly correct any problems found to allow cross exchange
> Testing cross exchange

- permissions.yaml
- src/yaml/motokloss/26675-jubiler.yaml
- src/yaml/motokloss/26683-motozbyt-office.yaml
- src/yaml/motokloss/26823-victoria-hotel.yaml
- src/yaml/motokloss/26936-w2w-multi-storey-car-park.yaml
- src/yaml/motokloss/27291-parking-lots-road-set-and-car-props.yaml
- src/yaml/motokloss/27333-marszalkowska-street-74.yaml
- src/yaml/motokloss/27876-government-office.yaml
- src/yaml/motokloss/28082-pkp-warsaw-station-halt.yaml
- src/yaml/motokloss/28174-przyjaciol-avenue-3.yaml
- src/yaml/motokloss/28374-zgoda-guesthouse.yaml
- src/yaml/motokloss/28665-smulikowskiego-13-warsaw.yaml
- src/yaml/motokloss/28665-smulikowskiego-13.yaml
- src/yaml/motokloss/28901-barges.yaml
- src/yaml/motokloss/28963-solaris-vacanza-12-and-interurbino-12-automata-props.yaml
- src/yaml/motokloss/28978-prochnika-8c.yaml
- src/yaml/motokloss/29002-house-of-artist.yaml
- src/yaml/motokloss/29035-6-sierpnia-28.yaml
- src/yaml/motokloss/29135-wsp-warsaws-nursing-school.yaml
Add content from [moto.kloss](https://community.simtropolis.com/profile/422335-motokloss/content/?type=downloads_file).
> metadata: add moto.kloss's content

- src/yaml/maloskero/31500-brazilian-simple-houses-and-small-shops.yaml
- src/yaml/maloskero/31909-brazilian-tenements-and-medium-stores.yaml
Add [Maloskero's](https://community.simtropolis.com/profile/297147-maloskero/content/?type=downloads_file) content.
> metadata: add Maloskero's content

- scripts/sc4d.js
- src/yaml/adrianor/24872-residential-building.yaml
- src/yaml/adrianor/24892-peruvian-building.yaml
- src/yaml/adrianor/31284-rs-pack-santiaguino.yaml
- src/yaml/adrianor/31294-css-pack-santiaguino.yaml
- src/yaml/adrianor/31311-rss-mini-pack-santiaguino.yaml
- src/yaml/adrianor/31322-coss-pack-porteno.yaml
- src/yaml/adrianor/31364-csss-pack-limeno.yaml
- src/yaml/adrianor/31388-rss-pack-santiaguino.yaml
Add [Adrianor](https://community.simtropolis.com/profile/329305-adrianor/content/?type=downloads_file)'s content.
> metadata: add Adrianor's content

- src/yaml/nbvc/24528-modular-breakwater-set.yaml
- src/yaml/nbvc/26574-surfers.yaml
- src/yaml/nbvc/28146-divers-and-boats.yaml
- src/yaml/nbvc/28477-sailboats.yaml
- src/yaml/nbvc/28951-marina.yaml
- src/yaml/nbvc/29045-modular-marina-addon.yaml
- src/yaml/nbvc/29498-boats-and-buoys.yaml
- src/yaml/nbvc/29870-marina-round-corners.yaml
- src/yaml/nbvc/marina-collection-pack.yaml
This PR is for updating NBVC Marina mods and inserting a download that acts as a single installer
> NBVC Marina Upgrade

- src/yaml/ceafus-88/26153-vet.yaml
- src/yaml/glenni/13348-14-story-brutalist-hospital.yaml
- src/yaml/jasoncw/20030-central-police-station.yaml
- src/yaml/jasoncw/21823-air-filter.yaml
- src/yaml/jasoncw/27012-frosch-elementary.yaml
- src/yaml/mattb325/33875-boaty-mcboatface.yaml
- src/yaml/mattb325/33884-super-yacht.yaml
- src/yaml/mattb325/33886-sailing-boat.yaml
- src/yaml/mattb325/33909-offshore-pontoon.yaml
- src/yaml/nofunk/29018-milwaukee-engine-co-1.yaml
Closes #242 and closes #243, plus adjusts some other subfolders as well.
> metadata: adjust subfolders

- src/yaml/andisart/10994-one21-apartment-tower.yaml
- src/yaml/andisart/18485-1-andis-plaza.yaml
- src/yaml/andisart/18694-lighthouse-tower-dubai.yaml
- src/yaml/andisart/21033-okhta-center.yaml
- src/yaml/andisart/21074-sunken-lots-pack.yaml
- src/yaml/andisart/29406-gt-tower-east.yaml
- src/yaml/andisart/32179-iris-bay.yaml
- src/yaml/andisart/33415-avenue-roundabout-megapack.yaml
Add [Andisart](https://community.simtropolis.com/profile/46565-andisart/?do=content)'s content not already included in sc4pac.
> metadata: add Andisart's content

- scripts/sc4d.js
- src/yaml/antoine-sc/18757-prop-pack.yaml
- src/yaml/benno2005/26644-fire-station.yaml
- src/yaml/benno2005/26651-small-row.yaml
- src/yaml/benno2005/26700-old-indoor-market.yaml
- src/yaml/benno2005/26775-construction-site.yaml
- src/yaml/benno2005/26856-kwik-fit.yaml
- src/yaml/benno2005/26945-kwik-fit-two.yaml
- src/yaml/benno2005/27574-bus-stop-pack.yaml
- src/yaml/benno2005/28054-main-bus-station.yaml
- src/yaml/benno2005/28128-sidewalk-bus-stops.yaml
- src/yaml/benno2005/28772-park-4x8.yaml
- src/yaml/benno2005/28795-park-20x10.yaml
Add content by [benno2005](https://community.simtropolis.com/profile/311288-benno2005).
> metadata: add benno2005's content

- src/yaml/andisart/10994-one21-apartment-tower.yaml
- src/yaml/andisart/18485-1-andis-plaza.yaml
- src/yaml/andisart/18694-lighthouse-tower-dubai.yaml
- src/yaml/andisart/21033-okhta-center.yaml
This PR is needed to update the AndisArt content and insert cross-references between STEX and SC4E
> Update AndisArt content

- src/yaml/paulsawyer/28771-maxis-seasonal-residential-commercial-lots.yaml
Adds the only content from PaulSawyer
> Add PaulSawyer content

- src/yaml/deezedgod/35337-diego-del-llano-growables-2017-pack-two.yaml
- src/yaml/deezedgod/35340-diego-del-llano-growables-2018-pack.yaml
- src/yaml/deezedgod/35342-diego-del-llano-growables-2019-pack.yaml
This PR serves to bring the CAM Revival Project into SC4Pac.
> Add CAM Revival Project
